#!/bin/bash
#
# This script installs the neo4j account 'simengine'
# and sets a new password for the default account.
#
# CTyler 2018-06-06

echo "===== $(basename $0)"
sudo neo4j start
sleep 4
echo "CALL dbms.changePassword('neo4j-simengine'); CALL dbms.security.createUser('simengine', 'simengine', false);"|sudo cypher-shell -u neo4j -p neo4j
STATUS=$?
sudo neo4j stop
exit $STATUS

