#!/bin/bash
# setup redis keyspace events
echo "===== $(basename $0)"
echo "Setting up redis keyspace events..."
sudo sed -i 's/^notify-keyspace-events.*/notify-keyspace-events "E$"/' /etc/redis.conf
